### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mrexodia**
Added information on the x64dbg port.

---

This change is [Reviewable](https://reviewable.io/reviews/nologic/idaref/4)

### CODE REVIEW

**Comment by nologic** [comment]
Please update your fork's readme file to describe how one would use your modifications and then I'll add your line.

**Comment by mrexodia** [comment]
Okay cool, will do!

**Comment by mrexodia** [comment]
I updated the readme file with screenshots and a description on how to use this feature. Basically I dump the information in the `.sql` to a JSON file which is used by x64dbg to show the documentation.

https://github.com/x64dbg/idaref/blob/x64dbg/README.md

**Comment by nologic** [comment]
Great work!

**Pull request merged**
